"""Initial migration

Revision ID: 63163d0c7973
Revises:
Create Date: 2025-07-28 19:49:51.836386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63163d0c7973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('default_resume_id', sa.Integer(), nullable=True),
    sa.Column('default_cover_letter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_cover_letter_id'], ['cover_letter.id'], ),
    sa.ForeignKeyConstraint(['default_resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('resume')
    op.drop_table('cover_letter')
    # ### end Alembic commands ###
