# Generated by Django 5.2.4 on 2025-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="link",
            field=models.URLField(default=""),
        ),
    ]
