# Generated by Django 5.2.5 on 2025-08-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobposting_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="id",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="posting_date",
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="link",
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
