# Generated by Django 5.2.4 on 2025-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobposting_scrapabledomain_user_coverletter_resume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="name",
            field=models.CharField(default="default_cover_letter_name", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(default="default_resume_name", max_length=255),
        ),
    ]
