# Generated by Django 5.2.5 on 2025-08-13 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_jobposting_id_remove_jobposting_posting_date_and_more"),  # noqa
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"),
                                 ("failure", "Failure")],
                        max_length=10,
                    ),
                ),
                ("jobs_found", models.IntegerField(default=0)),
                ("details", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
