# Generated by Django 5.2.5 on 2025-08-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_hiddencompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="userjobinteraction",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
