# Generated by Django 5.2.5 on 2025-08-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_userjobinteraction_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchableJobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
