# Generated by Django 5.2.5 on 2025-08-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_searchablejobtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="posting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
