# Generated by Django 5.2.5 on 2025-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_jobposting_posting_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="days_in_office",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="work_arrangement",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "Onsite"),
                ],
                default="onsite",
                max_length=10,
            ),
        ),
    ]
