# Generated by Django 5.2.5 on 2025-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jobposting_days_in_office_jobposting_location_and_more"),  # noqa
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_work_arrangement",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "Onsite"),
                    ("any", "Any"),
                ],
                default="any",
                max_length=10,
            ),
        ),
    ]
