# Generated by Django 5.2.5 on 2025-08-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_preferred_work_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
