# Generated by Django 5.2.5 on 2025-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_jobposting_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="location",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="work_arrangement",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="locations",
            field=models.JSONField(default=list),
        ),
    ]
