# Generated by Django 5.2.5 on 2025-08-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_jobposting_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="details_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
