# Generated by Django 5.2.5 on 2025-08-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_jobposting_details_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_work_arrangement",
            field=models.JSONField(default=list),
        ),
    ]
