# Generated by Django 5.2.5 on 2025-09-12 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_preferred_work_arrangement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(default=datetime.time(3, 0))),
            ],
        ),
    ]
