name: Python Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Scan for vulnerabilities
      run: safety check --file=requirements.txt
    - name: Run black
      run: black --check .
    - name: Run flake8
      run: flake8 .
    - name: Run mypy
      run: mypy .
    - name: Run pydocstyle
      run: pydocstyle .
    - name: Run bandit
      run: bandit -r .
    - name: Run pytest
      run: pytest
